contact: https://www.turing.ac.uk/research/research-engineering

title: "MPHYG001: Research Software Engineering With Python"
includeleftnav: True
short: MPHYG001

defaults:
  - scope: {path: ""}
    values: {layout: default}

baseurl: /rsd-engineeringcourse

crumbs:
  - link: http://www.ucl.ac.uk/ISD
    text: ISD
  - link: http://www.ucl.ac.uk/isd/services
    text: Our services
  - link: http://www.ucl.ac.uk/isd/services/research-it
    text: Research IT
  - link: http://www.ucl.ac.uk/isd/services/research-it/training
    text: Training

markdown: redcarpet
redcarpet:
  extensions: ["strikethrough","tables"]


include:
  - "ch04packaging/greetings/doc/_static"
  - "ch04packaging/greetings/doc/_static"
  - "ch04packaging/greetings/doc/_modules"
exclude:
  - "*/*.nbconvert.ipynb"
  - "*/*.v2.ipynb"
  - "combined_files"
  - "combined.ipynb"
