#######################################################################################
# Book settings
title: Research Software Engineering with Python
author: The Alan Turing Institute
logo: docs/ATI_logo_black_W1024px.png
only_build_toc_files: true

#######################################################################################
# Execution settings
execute:
  execute_notebooks: force

#######################################################################################
# HTML-specific settings
html:
  favicon: docs/favicon.ico
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  extra_navbar: <p>Download notes as <a href="/pdf/book.pdf">PDF</a>.</p><p>Powered by <a href="https://jupyterbook.org">Jupyter Book</a>.</p>

#######################################################################################
# Git repository settings
repository:
  url: https://github.com/alan-turing-institute/rsd-engineeringcourse
